g++ -c a.cpp #Compile a into object file
g++ -c hello.cpp #Compile hello into object file
g++ a.o hello.o -o hello.exe #Link the object files into a single executable
#A fentiek jelen esetben megegyeznek az alábbival: g++ a.cpp hello.cpp -o hello.exe